### ISSUE TITLE
Missing File?

### ISSUE THREAD

**Issue by miklb** [EvanHerman/local-wordpress-bash-manager#1]
https://github.com/EvanHerman/automated-local-wordpress-install/blob/13d395d5cd362077a87f9e8773f9538ec81f0436/Scripts/install-wp.sh#L4

I haven't actually installed anything yet, but reading through the install script I don't see where this comes from or is going. 

It is also completely possible I'm mis-reading the scripts.

**Comment by EvanHerman** [comment]
Hey @miklb 

You are correct - that is a typo and should actually be referencing [wp-config.sh](https://github.com/EvanHerman/automated-local-wordpress-install/blob/master/Scripts/wp-config.sh).

Before deciding to open source this I was running with a different set of naming conventions, but seeing as it's not necessarily Valet reliant I switched up the names when pushing to Github.

I seem to have forgotten to update the file name inside that script - so thank you for catching that!
